# PostgreSQL configuration for Rails 8
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  # Add configurations for other databases
  cable:
    url: <%= ENV['DATABASE_URL'] %>
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  # If you're using solid_queue or solid_cache
  queue:
    url: <%= ENV['DATABASE_URL'] %>
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  cache:
    url: <%= ENV['DATABASE_URL'] %>
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>